### ISSUE TITLE
Add an option for including the request into the template context, similar to what Pyramid does.

### ISSUE THREAD

**Issue by neRok00** [aio-libs/aiohttp-mako#4]
As per title, this would be a handy feature.

**Comment by jettify** [comment]
I guess we need something similar to aiohttp_jinja2 context processors. See https://github.com/aio-libs/aiohttp_jinja2/issues/13 for discussion and https://github.com/aio-libs/aiohttp_jinja2/pull/14 for implementation.

Would you like to propose pull request?
